[package]
name = "vpn-core"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
crc32fast = "1.4.2"
flexi_logger = "0.29.8"
libc = "0.2.171"
log = "0.4.27"
nix = { version = "0.29.0", features = ["socket"] }
serde = { version = "1.0.219", features = ["derive"] }
