[package]
name = "veil-clientd"
description = "The VEIL client daemon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
tracing.workspace = true
veil-common.workspace = true

[lints]
workspace = true
